@TodoApi_HostAddress = http://localhost:5135

GET {{TodoApi_HostAddress}}/api/todoitems
Accept: application/json
Authorization: Bearer CfDJ8BQ9CszF4s5Hm6rUEHXWm77a75fYymIZZwJ3XDCGNeMTX96dR7snq7ZzXl0t6GW4J4oRos4HOTwFZ1h_MzB0AV_QCIMtFg3dUVWJmIHSjqDRe2YXgblEXsZu4cAzvf84zEsX1xKJS5bYxdKEOjh0AAZPmeC6ujIceHUJIGqtVY-4uGJLIPASaGFNz8M1L36hodroxq8LjeXNA292fsbOjNUjOW0n0INQU9TjhaAk2oMlpRIz8njWmC8QJZduQgSlLRNoL2uoDHCjEtfzt0WENC2UWBsJPDYVLXjMR4Zb_rtzGDD50cV_Un1OSUrnGjOHHiU9UelvBXCmjm6ffyI3HDxnlwYI4YoiTjNH4rjbXsJf5Z2FZBsg4NvOuodzfwcblS0Zl_7Oas9ZrDnarXkBLrxi8Z3Gwn1YxwsAX4XSibuyjjf0WFnAvp_Ft37MpHJO_3ChbT4nt27SfgSnKXcmwwuvtKu-7HifrRIPaS6ZbVJhXw9koxpw7rG84VlaOdvU0FMvZgIpvPis5J1h3xbZCgLhtgn6HWCV0XnpNJo-VCKWk8zEasZ1AsQGY0Whk8pi4adTHyb7l6jITDMdIGG30jHpbnhLQ-dduNYjlpaK_QNjbaAMLyA2aJy-2PLm9wQH3JevbzJ9sp9BxHNWM0sVeKFOfE605R7b3POw0mi3xzM2d0jJ1KX1-RyxeoiBBTMR_g
###
